---
- name: Install packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - epel-release
    - git
    - gcc-c++
    - jansson
    - jansson-devel
    - graphviz
    - graphviz-devel
    - gtk2
    - gtk2-devel
    - libxml2
    - libxml2-devel
    - libcurl
    - libcurl-devel
    - openssl
    - openssl-devel
    - readline
    - readline-devel
    - libssh2
    - libssh2-devel
    - globus-common-devel
    - globus-gsi-credential-devel
    - globus-gsi-proxy-core-devel
    - globus-gssapi-gsi-devel
    - voms-devel
    - automake
    - autoconf
    - libtool

- name: Clone git repo ophidia terminal
  git: repo={{ item.repo }} dest={{ item.dest }} clone=yes
  with_items:
    - { repo: "https://github.com/indigo-dc/ophidia-terminal.git", dest: "/usr/local/ophidia-terminal" }

- name: Run bootstrap
  command: ./bootstrap chdir=/usr/local/ophidia-terminal

- name: Run configure
  command: ./configure --prefix=/usr/local chdir=/usr/local/ophidia-terminal

- name: Run make install
  command: make install chdir=/usr/local/ophidia-terminal
